from typing import Any

def __getattr__(self, name: str) -> Any: ...  # type: ignore[misc]  # incomplete
def deepupdate(original, update): ...
def remove_none(mapping): ...
def get_appcontext(): ...
def load_info_from_docstring(docstring, *, delimiter: str = ...): ...
def unpack_tuple_response(rv): ...
def set_status_and_headers_in_response(response, status, headers) -> None: ...
def prepare_response(response, spec, default_response_content_type) -> None: ...
