name: Release Main

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv-setup wheel twine

      - name: Install semantic release slack bot
        run: npm i semantic-release-slack-bot semantic-release-pypi

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_NT_SEMANTIC_RELEASE_PROD }}
          PYPI_TOKEN: ${{ secrets.GH_PYPI_TOKEN }}
        run: npx semantic-release
